trigger:
- main

pool:
  vmimage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Copiar o arquivo WebApp.zip para uma pasta específica
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.artifactStagingDirectory)'
    Contents: 'WebApp.zip'
    TargetFolder: '$(build.artifactStagingDirectory)/s3'

- task: S3Upload@1
  inputs:
    awsCredentials: 'artefact-publish'
    regionName: 'us-east-1'
    bucketName: 'guilherme.rocha-artefact'
    globExpressions: '**'
    filesAcl: 'public-read-write'
    createBucket: true
