name: SecondPipeline 

trigger: none

# this pipeline will be triggered by another pipeline
resources:
  pipelines:
  - pipeline: previous-pipeline-trigger   # Name of the pipeline resource
    source: First-Pipeline-yaml # Name of the pipeline referenced by the pipeline resource
    trigger: true # enable the trigger

pool:
  name: Self-hosted

steps:
  - powershell: |
      echo teste