trigger:
- main

pool:
  name: Self-hosted

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactStagingDirectory: '$(Build.SourcesDirectory)/staging'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(shortOutputPath)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: IISWebAppManagementOnMachineGroup@0
  inputs:
    IISDeploymentType: 'IISWebsite'
    ActionIISWebsite: 'StopWebsite'
    StartStopWebsiteName: 'Default Web Site'

- powershell: |
    Expand-Archive -Path "$(shortOutputPath)\WebApp.zip" -DestinationPath "$(Build.ArtifactStagingDirectory)\WebApp"

# - task: IISWebAppManagementOnMachineGroup@0
#   inputs:
#     IISDeploymentType: 'IISWebsite'
#     ActionIISWebsite: 'CreateOrUpdateWebsite'
#     WebsiteName: 'Default Web Site'
#     WebsitePhysicalPath: 'C:\Users\guilherme\Desktop\IIS-TEST'
#     WebsitePhysicalPathAuth: 'WebsiteWindowsAuth'
#     WebsiteAuthUserName: 'guilherme'
#     WebsiteAuthUserPassword:  ###

# - task: IISWebAppManagementOnMachineGroup@0
#   inputs:
#     IISDeploymentType: 'IISWebsite'
#     ActionIISWebsite: 'StartWebsite'
#     StartStopWebsiteName: 'Default Web Site'
