# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: Self-hosted

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\fullstack.zip" /p:DeployIisAppPath="Default Web Site"'

    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  
- task: IISWebAppManagementOnMachineGroup@0
  inputs:
    IISDeploymentType: 'IISWebsite'
    ActionIISWebsite: 'StopWebsite'
    StartStopWebsiteName: 'Default Web Site'


- powershell: |
    echo $(build.artifactStagingDirectory)
    Expand-Archive -Path $(build.artifactStagingDirectory)\fullstack.zip -DestinationPath "C:\Users\guilherme\Desktop\Fontes" -Force
    del C:\Users\guilherme\Desktop\Fontes\Content\C_C\agent\_work\8\s\Back\src\ProEvent.API\obj\Release\net5.0\PubTmp\Out\web.config
    copy \Users\guilherme\Desktop\Fontes\* \Users\guilherme\Desktop\IIS-TEST


- task: IISWebAppManagementOnMachineGroup@0
  inputs:
    IISDeploymentType: 'IISWebsite'
    ActionIISWebsite: 'StartWebsite'
    StartStopWebsiteName: 'Default Web Site'

